<a href="https://colab.research.google.com/github/heisenberg183/SoftComputing/blob/main/SCExp9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

def cartesian_product(matrix1, matrix2):
    # Cartesian product of two matrices
    cartesian_matrix = np.zeros((matrix1.shape[0] * matrix2.shape[0], matrix1.shape[1] * matrix2.shape[1]))
    for i in range(matrix1.shape[0]):
        for j in range(matrix1.shape[1]):
            for k in range(matrix2.shape[0]):
                for l in range(matrix2.shape[1]):
                    cartesian_matrix[i * matrix2.shape[0] + k, j * matrix2.shape[1] + l] = min(matrix1[i, j], matrix2[k, l])
    return cartesian_matrix

def max_min_composition(matrix):
    # Max-min composition based on the matrix
    composition_result = np.max(matrix, axis=1)
    return composition_result

# Example matrices
matrix1 = np.array([[0.7, 0.5], [0.4, 0.8]])
matrix2 = np.array([[0.6, 0.9], [0.3, 0.7]])

# Perform Cartesian product of matrices
cartesian_matrix = cartesian_product(matrix1, matrix2)

# Perform max-min composition
composition_result = max_min_composition(cartesian_matrix)

print("Matrix 1:")
print(matrix1)
print("\nMatrix 2:")
print(matrix2)
print("\nCartesian Product Matrix:")
print(cartesian_matrix)
print("\nMax-Min Composition Result:")
print(composition_result)


Matrix 1:
[[0.7 0.5]
 [0.4 0.8]]

Matrix 2:
[[0.6 0.9]
 [0.3 0.7]]

Cartesian Product Matrix:
[[0.6 0.7 0.5 0.5]
 [0.3 0.7 0.3 0.5]
 [0.4 0.4 0.6 0.8]
 [0.3 0.4 0.3 0.7]]

Max-Min Composition Result:
[0.7 0.7 0.8 0.7]
